package com.aiapkbuilder.app.util

import com.aiapkbuilder.app.data.model.*
import com.aiapkbuilder.app.data.service.AICodeGenerationService
import com.google.gson.Gson
import java.io.File
import javax.inject.Inject
import javax.inject.Singleton

@Singleton
class AICodeGenerator @Inject constructor(
    private val aiCodeGenerationService: AICodeGenerationService,
    private val codeGenerator: CodeGenerator,
    private val gson: Gson
) {

    suspend fun generateProjectPlan(request: GenerationRequest): GeneratedProjectPlan {
        return aiCodeGenerationService.analyzePromptAndPlan(request)
            .getOrElse { throw it }
    }

    suspend fun generateProjectSources(plan: GeneratedProjectPlan, projectId: String) {
        // Create project directory
        val projectDir = File("/data/data/com.aiapkbuilder.app/files/projects/$projectId")
        projectDir.mkdirs()

        // Save project plan
        val planJson = gson.toJson(plan)
        File(projectDir, "project_plan.json").writeText(planJson)

        // In a full implementation, this would generate all source files
        // For now, we create a marker file
        File(projectDir, "generated.marker").writeText("Project generated at ${System.currentTimeMillis()}")
    }

    /**
     * Generate a complete project using the new code generation system.
     */
    suspend fun generateCompleteProject(
        request: GenerationRequest,
        onProgress: (String) -> Unit = {}
    ): Result<GeneratedProjectFiles> {
        try {
            onProgress("Analyzing your request...")

            // Step 1: Analyze and plan
            val plan = aiCodeGenerationService.analyzePromptAndPlan(request)
                .getOrElse { throw it }

            onProgress("Creating project blueprint...")

            // Step 2: Create blueprint (this would be done by ProjectPlannerService)
            // For now, we'll create a simple blueprint

            onProgress("Generating source code...")

            // Step 3: Generate code using CodeGenerator
            val blueprint = createBasicBlueprint(plan)
            val generatedFiles = codeGenerator.generateProject(blueprint) { progress ->
                onProgress(progress)
            }.getOrElse { throw it }

            onProgress("Project generation complete!")

            return Result.success(generatedFiles)

        } catch (e: Exception) {
            return Result.failure(e)
        }
    }

    private fun createBasicBlueprint(plan: GeneratedProjectPlan): ProjectBlueprint {
        // This is a simplified blueprint creation
        // In a full implementation, this would use ProjectPlannerService
        return ProjectBlueprint(
            appName = plan.appName,
            packageName = plan.packageName,
            screens = plan.screens.map { screenSpec ->
                ScreenBlueprint(
                    name = screenSpec.name,
                    route = screenSpec.route,
                    type = ScreenType.DETAIL, // Simplified
                    components = screenSpec.uiComponents.map { component ->
                        ComponentSpec(
                            name = component,
                            type = ComponentType.CUSTOM,
                            properties = emptyMap(),
                            eventHandlers = emptyList()
                        )
                    },
                    dataBinding = DataBinding(
                        viewModelName = "${screenSpec.name.replace("Screen", "")}ViewModel",
                        stateType = "UiState",
                        eventType = "UiEvent"
                    ),
                    navigation = emptyList()
                )
            },
            viewModels = emptyList(), // Would be generated by planner
            repositories = emptyList(), // Would be generated by planner
            dataModels = emptyList(), // Would be generated by planner
            dependencies = plan.dependencies,
            permissions = plan.permissions,
            colorScheme = ColorScheme(plan.colorPrimary, plan.colorSecondary, "#FF5722"),
            databaseSchema = DatabaseSchema(emptyList()),
            apiClients = emptyList(),
            buildConfig = BuildConfigSpec(
                minSdk = plan.minSdkVersion,
                targetSdk = 34,
                versionCode = 1,
                versionName = "1.0.0",
                applicationId = plan.packageName,
                buildTypes = listOf("debug", "release"),
                features = plan.features
            )
        )
    }
}